### ISSUE TITLE
Extra Utilities Question

### ISSUE THREAD

**Issue by benneely** [duke-lungmap-team/lungmap-pipeline#2]
@whitews - In order to generate evaluations, I need to stash a few utility functions. Considering creating an `examples/utils` folder for this purpose. Please verify this is acceptable?

**Comment by whitews** [comment]
Yes, but maybe call it `eval` or something similar? We've got a lot of `utils` variants floating around between all the libs.

**Comment by benneely** [comment]
I will need to stash other things in here (e.g. things related to generating random shapes, etc.) can still put this under `eval`, but want to ensure you know what PRs are headed your way.

**Comment by whitews** [comment]
Shouldn't the shapes data go in the micap repo?

**Comment by benneely** [comment]
Anything related to `lungmap` specific examples will go in this repo. All other examples will go in the `micap` repo. Thanks!
