### ISSUE TITLE
Question about examples

### ISSUE THREAD

**Issue by benneely** [duke-lungmap-team/lungmap-pipeline#3]
I'm adding instructions to the README to tell users how to get their own copy of the data for running the example pipelines. However, currently the [lungmap-image-data](https://github.com/duke-lungmap-team/lungmap-image-data) repository only contains `20x` images. How will we handle the `60X` examples?

**Comment by whitews** [comment]
@benneely I've added the original 60x images to lungmap-image-data. Feel free to add the corrected versions there.

**Comment by benneely** [comment]
Thanks! Confirmed 60x script works with this new resource. Will add instructions for using `lungmap-image-data` to run all examples in this repo.
