### ISSUE TITLE
examples/run_pipeline.py fails

### ISSUE THREAD

**Issue by benneely** [duke-lungmap-team/lungmap-pipeline#4]
In debugging, it looks like this is failing in `cv2_extras.utils.find_border_by_mask`, specifically, for some contours the function `scipy.optimize.curve_fit` is being fed a range, which doesn't have a `shape` attribute. Let me know if you can replicate.

**Comment by whitews** [comment]
What data set are you using when you see this?

**Comment by benneely** [comment]
I've symlinked lungmap-image-data into a local folder called `data` (e.g. `ln -s /path/to/lungmap-image-data data`). Just pulled upstream to ensure the lungmap-image-data is up-to-date. I'm using python 3.6.8 and scipy version 1.3.0. Let me know if you can't replicate and need other info.

**Comment by whitews** [comment]
Yes, I can replicate. There was a bug in cv2-extras that is now fixed. If you can verify it is working for you we can close this.

**Comment by benneely** [comment]
Verifying fix, `examples/run_pipeline.py` works.
