### ISSUE TITLE
Trouble reading ontology .owl file

### ISSUE THREAD

**Issue by benneely** [duke-lungmap-team/lungmap-pipeline#6]
Using `ontospy==1.9.8.2`, I'm getting a fatal error in `gui.utils` when trying to instantiate an ontospy.Ontospy object. The error is:

```
Fatal error parsing graph <../resources/lung_ontology.owl>
(using RDF serializations: ['xml'])
```

**Comment by whitews** [comment]
Ben, what operating system are you using? Can you post the entire stack trace?

**Comment by benneely** [comment]
I'm running on Ubuntu 18.04. My plan was to create an equivalent docker image with wine to compile the windows executable. Before starting down that path, I just wanted to run locally. Here is the entire stack trace running the module as a script. Interested to know if you delete your pickled ontology, can you replicate?

```
lungmap-pipeline$ python -m gui.lungmap_pipeline.py
----------
Fatal error parsing graph <../resources/lung_ontology.owl>
(using RDF serializations: ['xml'])
----------
TIP: You can try one of the following RDF validation services
<http://mowl-power.cs.man.ac.uk:8080/validator/validate>
<http://www.ivan-herman.net/Misc/2008/owlrl/>
Traceback (most recent call last):
  File "lungmap-pipeline/gui/utils.py", line 9, in <module>
    f = open(PICKLED_ONTOLOGY, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '../resources/lung_ontology.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lungmap-pipeline/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "lungmap-pipeline/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "lungmap-pipeline/gui/lungmap_pipeline.py", line 11, in <module>
    from gui import utils as gui_utils
  File "lungmap-pipeline/gui/utils.py", line 16, in <module>
    f = open(PICKLED_ONTOLOGY, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '../resources/lung_ontology.pkl'
```

**Comment by whitews** [comment]
Just deleted the pkl file and it still works for me. I'm using the exact same version of ontospy, but I am using  Python 3.7. Also, what version of rdflib do you have? I have 4.2.2.

**Comment by benneely** [comment]
I'm using the same setup (Python 3.7.3 and rdflib 4.2.2). I just cloned this repo into a disposable directory and can confirm the same error. May need to take this offline to QC further? Let me know if you have other ideas.

**Comment by whitews** [comment]
This turned out to be an import issue, fixed in latest commit
