### ISSUE TITLE
Windows 10 Bug: Generate Candidate Contours Triggers new LungMAP Region Generator screen

### ISSUE THREAD

**Issue by benneely** [duke-lungmap-team/lungmap-pipeline#7]
On Windows 10, upon selecting default settings and then selecting the image `*_001.tif` and then pressing `Find Regions`, the pipeline starts to find contours and we see the following in the console:
```
Pre-processing test image...
90 color candidates found, kernel: (15, 15)
```
at which point a new blank LungMAP Region Generator Image screen populates. This is occurring in `lungmap_pipeline.Application.run_segmentation`. Not sure if threading from find_regions is the culprit. Let me know if you have ideas about tracking this down.

**Comment by whitews** [comment]
Sounds like it's an issue with micap and Windows. So you see no further output on the console? No errors?  What if you try your shapes data in micap on Windows?

**Comment by benneely** [comment]
This is a multiprocessing issue that seems to occur on Windows, but not Linux? Would like to understand more about that, but in the meantime. This proposed solution will work for us: https://stackoverflow.com/questions/46674498/tkinter-is-opening-multiple-gui-windows-upon-file-selection-with-multiprocessing. I will submit a PR now.

**Comment by whitews** [comment]
Nice, sounds like a rather easy fix.

**Comment by whitews** [comment]
@benneely I've merged this. Does this mean everything now runs okay in Windows?

**Comment by benneely** [comment]
I'm working with PyInstaller now to get an executable ready. We should discuss what a full test suite includes (so there are no surprises).  Right now I:

(1) Load Images
(2) Find Regions
(3) Label Bronchioles and Pulmonary Veins
(4) Hide current label
(5) Hide other labels
(6) Hide unlabelled regions
(7) Delete one region
(8) Show deleted regions
(9) Save Regions

**Comment by whitews** [comment]
That covers most of the functionality. What about the pre-processing?

**Comment by benneely** [comment]
Will add that and call that 100% coverage?

**Comment by whitews** [comment]
I believe that covers all the current functionality.

**Comment by benneely** [comment]
Closing as all functionality is as expected on Windows 10. Will work on executable and issues related elsewhere.
